spring.application.name=guess-the-word
spring.datasource.url=jdbc:mysql://localhost:3306/guess_the_word
spring.datasource.username=root
spring.datasource.password=YOUR_PASSWORD

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true